server:
  port: 8080
  servlet:
    session:
      timeout: 1800 # 设置session超时时间

spring:
    datasource:
        name: guoxm
        url: jdbc:postgresql://127.0.0.1:5432/robot
        username: robot
        password: robot
        driver-class-name: org.postgresql.Driver

mybatis:
    type-aliases-package: org.guoxm.mybatis.expand
